SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE SIWEPE.`abonos`;
TRUNCATE SIWEPE.`app_meta`;
TRUNCATE SIWEPE.`calificaciones`;
TRUNCATE SIWEPE.`categorias`;
TRUNCATE SIWEPE.`clientes_empresa`;
TRUNCATE SIWEPE.`comanda_items`;
TRUNCATE SIWEPE.`comandas`;
TRUNCATE SIWEPE.`compras`;
TRUNCATE SIWEPE.`config`;
TRUNCATE SIWEPE.`creditos`;
TRUNCATE SIWEPE.`cuentas_pagar`;
TRUNCATE SIWEPE.`empresas`;
TRUNCATE SIWEPE.`facturas`;
TRUNCATE SIWEPE.`gastos`;
TRUNCATE SIWEPE.`mensajes`;
TRUNCATE SIWEPE.`mesas`;
TRUNCATE SIWEPE.`movimientos`;
TRUNCATE SIWEPE.`movimientos_caja`;
TRUNCATE SIWEPE.`notificacion_lecturas`;
TRUNCATE SIWEPE.`onboarding_sessions`;
TRUNCATE SIWEPE.`pagos_cuenta_pagar`;
TRUNCATE SIWEPE.`password_resets`;
TRUNCATE SIWEPE.`pedido_items`;
TRUNCATE SIWEPE.`pedidos`;
TRUNCATE SIWEPE.`productos`;
TRUNCATE SIWEPE.`promociones`;
TRUNCATE SIWEPE.`proveedores`;
TRUNCATE SIWEPE.`registros_pendientes`;
TRUNCATE SIWEPE.`turnos_caja`;
TRUNCATE SIWEPE.`ventas`;
DELETE FROM SIWEPE.users WHERE email <> 'jr4419543@gmail.com';
ALTER TABLE SIWEPE.users AUTO_INCREMENT = 2;
SET FOREIGN_KEY_CHECKS = 1;
SELECT id, nombre, email, role, super_admin FROM SIWEPE.users;
